name = "Magical"
grammar = "magical"
path_suffixes = ["mgcl"]
line_comments = ["// "]
tab_size = 2
hard_tabs = false

[brackets]
pairs = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] }
]
